# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020-2023 Vincent Guittot <vincent.guittot@linaro.org>
# Copyright (C) 2020 Parth Shah <parth@linux.ibm.com>
# Copyright (C) 2023 Peter Jung <admin@ptr1337.dev> (CachyOS)
# Copyright (C) 2025-2026 AxionOS

MODULE_NAME := latency_sched

obj-m += $(MODULE_NAME).o

$(MODULE_NAME)-y := \
	latency_sched_main.o

ccflags-y += -I$(src) -I$(src)/include
